<?php
return [
    'YOUR_SERVICE_NAME_HERE' => [
        'YOUR_API_KEY_NAME_HERE'      => 'YOUR_API_KEY_VALUE_HERE',
        'YOUR_API_SECRET_NAME_HERE'   => 'YOUR_API_SECRET_VALUE_HERE',
        'YOUR_BUCKET_NAME_HERE'       => 'YOUR_BUCKET_VALUE_HERE',
        'YOUR_REGION_NAME_HERE'       => 'YOUR_REGION_VALUE_HERE',
        'YOUR_ENDPOINT_NAME_HERE'     => 'YOUR_ENDPOINT_VALUE_HERE',
    ]
];