<?php
// YOUR_SESSION_START_HERE

// YOUR_SESSION_ARRAY_CLEAR_LOGIC_HERE

// YOUR_SESSION_COOKIE_DESTROY_LOGIC_HERE

// YOUR_CUSTOM_SESSION_FILE_DELETE_LOGIC_HERE

// YOUR_SESSION_DESTROY_LOGIC_HERE

// YOUR_REDIRECT_LOGIC_HERE
header("Location: YOUR_LOGIN_PAGE_URL_HERE");
exit();
?>